"""T6 — Integration test with real Git.

End-to-end exercise of the three layers (OKF / CCDD / Postal) across two agent
subprocesses, versioned by real git commits in an isolated tempdir.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile

import pytest

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Subtrees that define the prototype. `.postal/` is intentionally NOT copied:
# it is runtime state regenerated by the agents inside the tempdir.
_TREES = ("okf", ".ccdd", "postal", "agents")

_IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache")


def _run_agent(script_name: str, cwd: str) -> subprocess.CompletedProcess:
    """Run the COPIED agent script inside `cwd` so its `_REPO_ROOT` resolves to
    `cwd` (agent scripts derive _REPO_ROOT from their own __file__)."""
    script = os.path.join(cwd, "agents", script_name)
    return subprocess.run(
        [sys.executable, script],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=120,
    )


def _git(*args: str, cwd: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 0, (
        f"git {' '.join(args)} failed (exit {result.returncode})\n"
        f"stdout={result.stdout}\nstderr={result.stderr}"
    )
    return result.stdout


def _setup_temp_repo() -> str:
    """Create a tempdir, copy the four subtrees, git init + baseline commit."""
    tmp = tempfile.mkdtemp(prefix="okf_t6_")
    for name in _TREES:
        src = os.path.join(_REPO_ROOT, name)
        dst = os.path.join(tmp, name)
        shutil.copytree(src, dst, ignore=_IGNORE)
    _git("init", cwd=tmp)
    # Self-contained identity so the test does not depend on the host's global
    # git config (e.g. CI runners have none).
    _git("config", "user.email", "test@carta.local", cwd=tmp)
    _git("config", "user.name", "Carta Test", cwd=tmp)
    _git("config", "commit.gpgsign", "false", cwd=tmp)
    _git("add", ".", cwd=tmp)
    _git("commit", "-m", "baseline", cwd=tmp)
    return tmp


def _seed_agent_b_identity(tmp: str) -> None:
    """Pre-establish Agent B's identity in the tempdir (setup, NOT an agent run).

    agent_a encrypts to the recipient's pubkey, which must be persisted before
    agent_a runs. Without this, agent_a would encrypt to a throwaway pubkey and
    agent_b could not decrypt (its private key would not match). This mirrors
    the T5 pattern (in-process `_ensure_identity`) but writes the file directly
    so the first agent SUBPROCESS stays `agent_a`, per the T6 spec.
    """
    from postal import generate_keypair

    priv, pub = generate_keypair()
    users_dir = os.path.join(tmp, ".postal", "users")
    os.makedirs(users_dir, exist_ok=True)
    payload = {"id": "agent-b", "public_key": pub, "private_key": priv}
    with open(os.path.join(users_dir, "agent-b.json"), "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)


# ---------------------------------------------------------------------------
# test_full_e2e_with_git
# ---------------------------------------------------------------------------
def test_full_e2e_with_git():
    tmp = _setup_temp_repo()
    try:
        # 0. Setup (not an agent run): persist Agent B's identity so agent_a can
        #    encrypt to a real, decryptable pubkey.
        _seed_agent_b_identity(tmp)

        # 1. Run agent_a -> exit 0, publishes one message.
        r_a = _run_agent("agent_a.py", tmp)
        assert r_a.returncode == 0, (
            f"agent_a exited {r_a.returncode}\nstdout={r_a.stdout}\nstderr={r_a.stderr}"
        )
        assert "message_id=" in r_a.stdout

        msgs_dir = os.path.join(tmp, ".postal", "messages")
        jsons = [n for n in os.listdir(msgs_dir) if n.endswith(".json")]
        assert len(jsons) == 1, f"expected 1 message after agent_a, got {jsons}"

        # 2. Commit agent-a's postal output.
        _git("add", ".postal/", cwd=tmp)
        _git("commit", "-m", "agent-a: published message", cwd=tmp)

        commits_after_a = _git("log", "--oneline", cwd=tmp).strip().splitlines()

        # 3. Run agent_b -> exit 0 + CONTEXT REPRODUCED.
        r_b = _run_agent("agent_b.py", tmp)
        assert r_b.returncode == 0, (
            f"agent_b exited {r_b.returncode}\nstdout={r_b.stdout}\nstderr={r_b.stderr}"
        )
        assert "CONTEXT REPRODUCED" in r_b.stdout, (
            f"CONTEXT REPRODUCED missing\nstdout={r_b.stdout}\nstderr={r_b.stderr}"
        )

        # 4. agent_b does NOT commit; commit count unchanged.
        commits_after_b = _git("log", "--oneline", cwd=tmp).strip().splitlines()
        assert len(commits_after_b) == len(commits_after_a), (
            "agent_b should not create a commit; "
            f"before={len(commits_after_a)} after={len(commits_after_b)}"
        )

        # 5. Exactly two commits: baseline + agent-a.
        assert len(commits_after_b) == 2, (
            f"expected 2 commits (baseline + agent-a), got {commits_after_b}"
        )
        assert "baseline" in commits_after_b[-1]
        assert "agent-a: published message" in commits_after_b[0]

        # 6. .postal/messages/ still has exactly 1 file (agent_b adds none).
        jsons_final = [n for n in os.listdir(msgs_dir) if n.endswith(".json")]
        assert len(jsons_final) == 1, (
            f"expected exactly 1 message file, got {jsons_final}"
        )
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# ---------------------------------------------------------------------------
# test_okf_sha_is_immutable
# ---------------------------------------------------------------------------
def test_okf_sha_is_immutable():
    from postal import compute_dir_sha

    okf_dir = os.path.join(_REPO_ROOT, "okf")

    sha1 = compute_dir_sha(okf_dir)
    sha2 = compute_dir_sha(okf_dir)
    assert sha1 == sha2, "compute_dir_sha is not deterministic"

    # Mutate a .md file -> SHA must change. Binary mode to preserve exact bytes
    # (text mode on Windows would translate LF<->CRLF and change the SHA even
    # after "reverting" the logical content).
    a_md = os.path.join(okf_dir, "index.md")
    with open(a_md, "rb") as f:
        original = f.read()
    try:
        with open(a_md, "ab") as f:
            f.write(b"\n\n<!-- T6 mutation probe -->\n")
        sha3 = compute_dir_sha(okf_dir)
        assert sha3 != sha1, "SHA did not change after mutating okf/"
    finally:
        with open(a_md, "wb") as f:
            f.write(original)
        assert compute_dir_sha(okf_dir) == sha1, "SHA did not revert cleanly"


# ---------------------------------------------------------------------------
# test_tampered_message_rejected
# ---------------------------------------------------------------------------
def test_tampered_message_rejected():
    tmp = tempfile.mkdtemp(prefix="okf_t6_tamper_")
    for name in _TREES:
        shutil.copytree(os.path.join(_REPO_ROOT, name), os.path.join(tmp, name),
                        ignore=_IGNORE)
    try:
        # 1. agent_a publishes a message.
        r_a = _run_agent("agent_a.py", tmp)
        assert r_a.returncode == 0, (
            f"agent_a exited {r_a.returncode}\nstderr={r_a.stderr}"
        )

        msgs_dir = os.path.join(tmp, ".postal", "messages")
        jsons = [n for n in os.listdir(msgs_dir) if n.endswith(".json")]
        assert len(jsons) == 1
        msg_path = os.path.join(msgs_dir, jsons[0])

        # 2. Tamper the payload (ciphertext) — breaks the POSTAL signature.
        with open(msg_path, "r", encoding="utf-8") as f:
            msg = json.load(f)
        msg["payload"] = "00" + msg["payload"][2:] if len(msg["payload"]) > 2 else "deadbeef"
        with open(msg_path, "w", encoding="utf-8") as f:
            json.dump(msg, f, indent=2, sort_keys=True)

        # 3. agent_b must reject it.
        r_b = _run_agent("agent_b.py", tmp)
        assert "POSTAL SIGNATURE INVALID" in r_b.stdout, (
            f"tampered message not rejected\nstdout={r_b.stdout}\nstderr={r_b.stderr}"
        )
    finally:
        shutil.rmtree(tmp, ignore_errors=True)