// Carta example — n8n lead-capture workflow (route: mcp)
//
// Webhook (POST /lead) -> Edit Fields (Set) adds received=true -> Respond to Webhook.
// Generated by a local model driven through the Carta loop, then validated and
// created with the n8n MCP (validate_workflow -> create_workflow_from_code).

import { trigger, node, workflow } from '@n8n/workflow-sdk';

const w = workflow('lead-capture', 'Carta - lead capture')
  .add(
    trigger({
      type: 'n8n-nodes-base.webhook',
      version: '2.1',
      config: {
        name: 'Webhook',
        position: [0, 0],
        parameters: {
          httpMethod: 'POST',
          path: 'lead',
          responseMode: 'responseNode',
        },
      },
    })
  )
  .to(
    node({
      type: 'n8n-nodes-base.set',
      version: '3.4',
      config: {
        name: 'Edit Fields (Set)',
        position: [1, 0],
        parameters: {
          mode: 'manual',
          assignments: {
            assignments: [
              { id: 'received', name: 'received', value: true, type: 'boolean' },
            ],
          },
          includeOtherFields: true,
        },
      },
    })
  )
  .to(
    node({
      type: 'n8n-nodes-base.respondToWebhook',
      version: '1.5',
      config: {
        name: 'Respond to Webhook',
        position: [2, 0],
        parameters: {
          respondWith: 'firstIncomingItem',
        },
      },
    })
  );

export default w;
