"""Agent REST — demonstrates the OKF REST route without an MCP server.

Full flow:
  1. Receives a task ('Publish a post titled OKF Demo and verify it exists').
  2. Calls tool_selector with --provider jsonplaceholder → gets skill + tool docs.
  3. Reads the 'route' field of each tool doc → all are 'rest'.
  4. Runs the sequence with the Bash adapter (curl): get_user → create_post → get_posts.
  5. Audit log of each call (okf_sha + ccdd_sha).
  6. Prints: TASK COMPLETE - route: rest - no MCP server required.

Usage (from repo root):
    python agents/agent_rest.py
"""
from __future__ import annotations

import hashlib
import json
import os
import sys

# Windows console defaults to cp1252 and can't encode → or accented chars.
# Force UTF-8 stdout so subprocess capture decodes cleanly.
try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

# Make repo root importable when run as a script.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)
# Make `agents/` importable for tool_selector.
if os.path.join(_REPO_ROOT, "agents") not in sys.path:
    sys.path.insert(0, os.path.join(_REPO_ROOT, "agents"))

from tool_selector import select_tools, load_okf_index  # noqa: E402
from bash import Bash, Allowlist, AuditLog, SharedFilesystem  # noqa: E402
from postal import compute_dir_sha  # noqa: E402

PROVIDER = "jsonplaceholder"
OKF_PATH = os.path.join(_REPO_ROOT, "okf", PROVIDER)
CCDD_CONTRACT = os.path.join(_REPO_ROOT, ".ccdd", "agent-a.yaml")
TASK = "Publish a post titled OKF Demo and verify it exists"
TITLE = "OKF Demo"
BODY = "Test post generated by agent_rest (REST route, no MCP)."
USER_ID = 1
BASE = "https://jsonplaceholder.typicode.com"


def _file_sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def _route_of(doc: dict) -> str:
    fm = doc.get("frontmatter", {}) or {}
    return str(fm.get("route", "") or "")


def _print(msg: str) -> None:
    print(msg, flush=True)


def main() -> int:
    okf_sha = compute_dir_sha(OKF_PATH)
    ccdd_sha = _file_sha256(CCDD_CONTRACT)
    _print(f"TASK: {TASK}")
    _print(f"OKF provider: {PROVIDER}  okf_sha={okf_sha[:12]}  ccdd_sha={ccdd_sha[:12]}")

    # 2. Select relevant docs (skill + tools).
    selected = select_tools(TASK, okf_path=OKF_PATH)
    if not selected:
        _print("ERROR: tool_selector returned no docs")
        return 1

    skill = selected[0]
    tool_docs = selected[1:]
    _print(f"Skill: {skill['name']}")
    _print(f"Selected tools: {[d['name'] for d in tool_docs]}")

    # 3. Read the 'route' field of each tool doc.
    routes = {_d["name"]: _route_of(_d) for _d in tool_docs}
    _print(f"Detected routes: {routes}")
    all_rest = all(r == "rest" for r in routes.values())
    if not all_rest:
        _print(f"ERROR: expected route=rest on all tools, got {routes}")
        return 1
    _print("All tools are route=rest → running over HTTP (curl), no MCP.")

    # 4. Run the sequence with Bash + allowlist + audit.
    allowlist = Allowlist.load_from_ccdd(CCDD_CONTRACT)
    audit = AuditLog(repo_path=_REPO_ROOT, enabled=True)
    bash = Bash(
        workdir=SharedFilesystem(),
        allowlist=allowlist,
        audit=audit,
        timeout=30,
    )

    # a. get_user → verify userId=1 exists.
    cmd_user = f"curl -s --max-time 10 {BASE}/users/{USER_ID}"
    r_user = bash.exec(cmd_user, okf_sha=okf_sha, ccdd_sha=ccdd_sha)
    _print(f"[get_user] exit={r_user['exit_code']} audit_id={r_user.get('audit_id')}")
    try:
        user = json.loads(r_user["stdout"])
        user_ok = int(user.get("id", -1)) == USER_ID
    except (json.JSONDecodeError, TypeError):
        user_ok = False
    _print(f"[get_user] userId={USER_ID} exists={user_ok}")

    # b. create_post → publish content.
    payload = json.dumps({"title": TITLE, "body": BODY, "userId": USER_ID})
    # single-quoted JSON is safe inside bash -c (no single quotes in payload)
    cmd_post = (
        f"curl -s --max-time 10 -X POST {BASE}/posts "
        f"-H 'Content-Type: application/json' -d '{payload}'"
    )
    r_post = bash.exec(cmd_post, okf_sha=okf_sha, ccdd_sha=ccdd_sha)
    _print(f"[create_post] exit={r_post['exit_code']} audit_id={r_post.get('audit_id')}")
    try:
        post = json.loads(r_post["stdout"])
        created_id = post.get("id")
    except (json.JSONDecodeError, TypeError):
        post = {}
        created_id = None
    _print(f"[create_post] created post id={created_id} title={post.get('title')}")

    # c. get_posts?userId=1 → verify it appears (author's list).
    cmd_list = f"curl -s --max-time 10 '{BASE}/posts?userId={USER_ID}'"
    r_list = bash.exec(cmd_list, okf_sha=okf_sha, ccdd_sha=ccdd_sha)
    _print(f"[get_posts] exit={r_list['exit_code']} audit_id={r_list.get('audit_id')}")
    try:
        posts = json.loads(r_list["stdout"])
        n_posts = len(posts) if isinstance(posts, list) else 0
    except (json.JSONDecodeError, TypeError):
        n_posts = 0
    _print(f"[get_posts] posts for userId={USER_ID}: {n_posts}")

    # 5. Audit summary.
    entries = audit.list_entries()
    _print(f"Audit: {len(entries)} calls recorded (okf_sha={okf_sha[:12]}, ccdd_sha={ccdd_sha[:12]})")

    # 6. Done.
    _print("TASK COMPLETE - route: rest - no MCP server required")
    return 0


if __name__ == "__main__":
    sys.exit(main())